[
    {
        "vegitables":[
            "patato",
            "onion",
            "ginger"
        ]
    },
    {
        "fruits":[
            "mango",
            "apple",
            "grapes"
        ]        
    },
    {
        "grains":[
            "rice",
            "wheat",
            "dall",
        ]
    }
]